name = "TerminalLoggers"
uuid = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
authors = ["Chris Foster <chris42f@gmail.com>"]
version = "0.1.7"

[deps]
LeftChildRightSiblingTrees = "1d6d02ad-be62-4b6b-8a6d-2f90e265016e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
LeftChildRightSiblingTrees = "0.1.1, 0.2"
ProgressLogging = "0.1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
